# Generated by Django 5.1.2 on 2024-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser", options={"ordering": ("-date_joined",)},
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="agreed_to_terms_and_p_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Town/City",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Country",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
